apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: skill-confirmed

deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: pawelgozdz/sc-auth
    docker:
      dockerfile: Dockerfile
      target: development
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .

portForward:
  - resourceType: deployment
    resourceName: sc-auth
    namespace: development
    port: 3000
    localPort: 3001
