apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: skill-confirmed

deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  tagPolicy:
    gitCommit: {}
  artifacts:

  - image: pawelgozdz/sc-auth
    docker:
      dockerfile: Dockerfile
      target: development
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .

  - image: pawelgozdz/sc-web-gateway
    docker:
      dockerfile: Dockerfile
      target: development
    context: api-gateway-web
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .


portForward:
  - resourceType: deployment
    resourceName: sc-auth-depl
    namespace: development
    port: 3001
    localPort: 3001

  - resourceType: deployment
    resourceName: sc-web-gateway-depl
    namespace: development
    port: 3000
    localPort: 3000

  - resourceType: deployment
    resourceName: sc-auth-pg-depl
    namespace: development
    port: 5432
    localPort: 5432
