kind: PersistentVolume
apiVersion: v1
metadata:
  name: sc-auth-pg-pv-vol  # Sets PV's name
  namespace: development
  labels:
    type: local  # Sets PV's type to local
    app: sc-auth-pg
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: development
  name: sc-auth-pg-pv-claim  # Sets name of PVC
  labels:
    app: sc-auth-pg
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 2Gi  # Sets volume size