apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-auth-depl
  namespace: development
  labels:
    app: sc-auth
spec:
  selector:
    matchLabels:
      app: sc-auth
  template:
    metadata:
      labels:
        app: sc-auth
    spec:
      containers:
      - name: sc-auth
        image: pawelgozdz/sc-auth
        ports:
        - containerPort: 3001
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: sc-auth-secret
      # initContainers:
      # - command:
      #   - npx
      #   - prisma
      #   - generate
      #   image: pawelgozdz/sc-auth
      #   imagePullPolicy: Never
      #   name: sc-auth
      #   envFrom:
      #     - secretRef:
      #         name: sc-auth-secret

---

apiVersion: v1
kind: Service
metadata:
  name: sc-auth-svc
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: sc-auth
  ports:
    - port: 3001